use_frameworks!

target 'michigan-ios-datasources_Example' do
  pod 'michigan-ios-datasources', :path => '../'

  target 'michigan-ios-datasources_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
